basePath: /
definitions:
  handler.Usuario:
    properties:
      email:
        example: teste@email.com
        type: string
      id:
        example: 1
        type: integer
      nome:
        example: italo
        type: string
    type: object
host: localhost
info:
  contact:
    email: italo.ods@hotmail.com
    name: Ítalo Oliveira
    url: https://github.com/dev-ita
  description: Isso é uma simples aplicação CRUD desenvolvida em GO
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Documentação para o Projeto Integrado II
  version: "1.0"
paths:
  /usuarios:
    post:
      consumes:
      - application/json
      description: Cria um usuário no banco de dados
      parameters:
      - description: Create order
        in: body
        name: usuario
        required: true
        schema:
          $ref: '#/definitions/handler.Usuario'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Usuario'
      summary: Cria um usuário
      tags:
      - users
swagger: "2.0"
