basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: your@email.com
    name: API Support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths: {}
swagger: "2.0"
